particle_filter:
  ros__parameters:
    # Particle filter parameters 
    max_particles: 4000                # Total number of particles for state estimation
    max_viz_particles: 60              # Maximum particles to visualize in RViz
    max_range: 5.0                      # Maximum laser range for sensor updates (meters)
    
    # Motion model noise parameters 
    motion_dispersion_x: 0.05          # Motion noise in x-direction (meters)
    motion_dispersion_y: 0.025         # Motion noise in y-direction (meters)
    motion_dispersion_theta: 0.25      # Motion noise in rotation (radians)
    
    # Robot geometry and sensor mounting
    lidar_offset_x: 0.288              # LiDAR X offset from base_link (meters) - 288mm forward from rear wheel
    lidar_offset_y: 0.0                # LiDAR Y offset from base_link (meters) - centered laterally
    wheelbase: 0.324                   # Distance between front and rear wheels (meters) 
    
    # Sensor model parameters
    z_hit: 0.75      # Weight for correct range measurements
    z_short: 0.01    # Weight for short range measurements
    z_max: 0.07      # Weight for max range measurements
    z_rand: 0.12     # Weight for random measurements
    sigma_hit: 8.0   # Standard deviation for hit measurements
    
    # Ray-casting parameters
    range_method: "cddt"        # (unused) Ray-casting method
    theta_discretization: 112   # (unused) Ray-casting angle discretization
    rangelib_variant: 2         # (unused) Ray-casting library variant
    angle_step: 18              # Laser scan downsampling step size
    squash_factor: 2.2          # Sensor model parameter for weight normalization
    
    # Performance and debugging
    fine_timing: 0              # Enable detailed timing output (0=false, 1=true)
    
    # Topic names
    scan_topic: "/scan"                # LaserScan topic for sensor updates
    odom_topic: "/odom"                # Real F1TENTH car odometry topic
    # odom_topic: "/ego_racecar/odom"  # F1TENTH Gym simulation odometry topic
    
    
    # Publishing options
    publish_odom: true                  # Whether to publish particle filter pose as odometry
    viz: true                           # Enable visualization markers in RViz
    
    # Update thresholds 
    update_min_distance: 0.0           # Minimum distance moved to trigger update (meters)
    update_min_angle: 0.0              # Minimum angle turned to trigger update (radians)
    
    # Frame IDs
    map_frame: "map"                   # Reference frame for the map
    base_frame: "base_link"            # Robot base frame for pose estimation
    laser_frame: "laser"               # Frame of the laser scanner
    
map_server:
  ros__parameters:
    # Map configuration - assuming map file is in particle_filter_cpp/maps
    # map: 'levine'                     # Levine Hall map option
    # map: 'Spielberg_map'              # Spielberg track map option
    map: 'map_1753950572'               # Map with SLAM
